name       : python-glad2
version    : 2.0.3
release    : 2
source     :
    - https://github.com/Dav1dde/glad/archive/refs/tags/v2.0.3.tar.gz : c891e4579ef13f500c57992250f3ea4257f59daece636a72b500d90ff137c080
license    : MIT
component  : programming.python
homepage   : https://glad.dav1d.de/
summary    : Multi-Language Vulkan/GL/GLES/EGL/GLX/WGL Loader-Generator based on the official specs
description: |
    Vulkan/GL/GLES/EGL/GLX/WGL Loader-Generator based on the official specifications for multiple languages.
setup      : |
    %python3_setup
install    : |
    %python3_install
