name       : python-glad2
version    : 2.0.2
release    : 1
source     :
    - https://github.com/Dav1dde/glad/archive/refs/tags/v2.0.2.tar.gz : 0326d59b1ccf8ccae1fface5bfb71bec1bb41fbe2341e722b31f6acac3068aeb
license    : MIT
component  : programming.python
homepage   : https://glad.dav1d.de/
summary    : Multi-Language Vulkan/GL/GLES/EGL/GLX/WGL Loader-Generator based on the official specs
description: |
    Vulkan/GL/GLES/EGL/GLX/WGL Loader-Generator based on the official specifications for multiple languages.
setup      : |
    %python3_setup
install    : |
    %python3_install
